# Introduction
  The Ness of Brodgar is a Neolithic Archaeological complex located in the Orkney Islands, Scotland, UK. The site is located on an isthmus acting as a land bridge between North and South mainland Orkney. This Ness is found in the heart of Neolithic Orkney, a UNESCO World Heritage site, and excavations have thus far shown the centricity of the site to Neolithic civilization in the North Atlantic. The complex is made up of massive stone structures that cover the entire width of the isthmus. The site was in use for hundreds of years at least as far back as 3000 BCE and the ongoing excavations make the Ness of Brodgar one of the most important archaeological excavations in the world.
	Due to the prehistoric nature of Neolithic Archaeology, interpretations of material culture have an outsized reliance on information gleaned from scientific study. As one of the largest active archaeological sites in the world, the Ness has attracted numerous archaeologists keen on using modern technology and innovative techniques to extract as much information as possible from the material culture. One of these projects has consisted of regular geochemical sampling of midden deposits within and around the excavated structures on the site. The technical name midden is given to refuse that has aggregated over hundreds of years. Midden is a figurative gold mine for contemporary archaeologists as waste piles not only possess countless artifacts, but also provide easy to identify layers that can be used to differentiate between occupational eras. Excavators on the site have been collecting samples of midden for geochemical analysis at regular intervals over the course of twelve dig seasons. Geochemical analysis has been conducted using X-ray fluorescent spectroscopy on each of these samples and has resulted in the largest database of geochemical spectral signatures in archaeological research. The data has largely only been used univariably to create heatmaps of specific elements of interest in specific structures on the site. Additionally, a few preliminary analyses have shown that excavator distinguished contexts are somewhat distinguishable when only analyzing and handful of datapoints. However, no machine learning or other more advanced statistical methods have been used to this point.
	If machine learning can be shown to effectively distinguish between contexts unsupervised, and the algorithm generated contexts are shown to be close to the excavator distinguished context this would add statistical backing to the accuracy of excavator expertise. Additionally, any information that could alter current understanding of the contextual makeup of the site from either an unsupervised or supervised standpoint would be greatly beneficial to archaeological domain experts when they present interpretations of uses for the Ness complex. 



