project:
  type: website

website:
  title: "Leveraging Principal Component Analysis for Enhanced Geochemical Signatures in Archaeological Research at the Ness of Broddgar"
  description: "A description of your project."
  site-url: https://averyPike.github.io/Capstone-Project
  repo-url: https://github.com/averyPike/Capstone-Project
  repo-branch: main

# Additional options
theme:
  light: "lightly"
  dark: "darkly"

format:
  html:
    theme:
      light: lightly
      dark: darkly
