project:
  type: website
  output-dir: "_site"

website:
  title: "Leveraging Principal Component Analysis for Enhanced Geochemical Signatures in Archaeological Research at the Ness of Broddgar"
  description: "A description of your project."
  output-dir: "_site"

# Additional options
theme:
  light: "lightly"
  dark: "darkly"

format:
  html:
    theme:
      light: lightly
      dark: darkly
