name: Publish to Quarto Pub

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: "1.3.340"  # Specify a stable version here
        
    - name: Publish to Quarto Pub
      env:
        QUARTO_PUB_TOKEN: ${{ secrets.QUARTO_PUB_TOKEN }}
      run: quarto publish quarto-pub
